mutation CreateDemoData @auth(level: NO_ACCESS) @transaction {
  user_insertMany(
    data: [
      {
        id: "550e8400-e29b-41d4-a716-446655440000"
        username: "demouser1"
        passwordHash: "passwordhash1"
        role: "admin"
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440001"
        username: "demouser2"
        passwordHash: "passwordhash2"
        role: "member"
      }
    ]
  )
  category_insertMany(
    data: [
      { id: "650e8400-e29b-41d4-a716-446655440000", name: "Category1" }
      { id: "650e8400-e29b-41d4-a716-446655440001", name: "Category2" }
    ]
  )
  medication_insertMany(
    data: [
      {
        id: "750e8400-e29b-41d4-a716-446655440000"
        name: "Medication1"
        dosage: "10mg"
        price: 10.0
        stockQuantity: 100
      }
      {
        id: "750e8400-e29b-41d4-a716-446655440001"
        name: "Medication2"
        dosage: "20mg"
        price: 20.0
        stockQuantity: 200
      }
    ]
  )
  medicationCategory_insertMany(
    data: [
      {
        medicationId: "750e8400-e29b-41d4-a716-446655440000"
        categoryId: "650e8400-e29b-41d4-a716-446655440000"
      }
      {
        medicationId: "750e8400-e29b-41d4-a716-446655440001"
        categoryId: "650e8400-e29b-41d4-a716-446655440001"
      }
    ]
  )
  inquiry_insertMany(
    data: [
      {
        id: "850e8400-e29b-41d4-a716-446655440000"
        subject: "Inquiry1"
        message: "Message1"
        submittedAt: "2024-04-03T12:34:56.000Z"
      }
      {
        id: "850e8400-e29b-41d4-a716-446655440001"
        subject: "Inquiry2"
        message: "Message2"
        submittedAt: "2024-04-04T12:34:56.000Z"
      }
    ]
  )
}